//
// Created by cherit on 12/27/20.
//

#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

#define SERVER_PORT 4201
#define MAX_CONFIRM_SIZE 255
#define MAX_ERROR_SIZE 400000

#define MAX_TYPE_SIZE 16
#define MAX_CONTENT_SIZE 400000
#define MAX_INCOMING_SIZE 400000

#define MSG_DELIMITER_CHR '\n'
#define MSG_DELIMITER_STR "\n"

#define DEBUG 1

#endif //SERVER_CONSTANTS_H
